### ISSUE TITLE
Can you export onnx model for dpt head depth estimate?

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [Tottowich/DeepDINO-DepthEstimation#1]

**Comment by Tottowich** [comment]
I look at it. It should be easily done by replicating the code in [this issue](https://github.com/facebookresearch/dinov2/issues/19) at the original repo.

**Comment by ZHEQIUSHUI** [comment]
not easy , i create a issue too,  strange error /cry
https://github.com/facebookresearch/dinov2/issues/213
